name: Run Bash Static Site Generator

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    bssg:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Install pandoc
              run: sudo apt install pandoc
            - name: Generate Site
              run: bash bssg.sh

    deploy:
        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}

        runs-on: ubuntu-latest
        needs: bssg
        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
